### ISSUE TITLE
Tab scaling

### ISSUE THREAD

**Issue by diomidov** [edemaine/comingle#183]
It would be nice if you could scale/zoom the contents of an individual tab.

The UI could be a pair of zoom buttons on the tab, or on the tabset. Unfortunately it doesn't seem to be possible to capture <kbd>Ctrl</kbd>+<kbd>+</kbd>/<kbd>-</kbd> or <kbd>Ctrl</kbd> + mouse wheel events unless the iframe is on the same domain :(

All tabs with the same (sub)domain name should probably share the scale factor. For example I might want to scale all `coauthor.csail.mit.edu` tabs by 120%.

This CSS seems to work:
```css
iframe {
  --scale: 1.2;
  width: calc(100% / var(--scale));
  height: calc(100% / var(--scale));
  transform: translate(-50%,-50%) scale(var(--scale)) translate(50%,50%);
}
```
